--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/JeroGamingYT-pm-pl/CustomBow
build-by-default: true
branches:
- pm4
- pm5
projects:
  CustomBow:
    path: ""
    icon: icon.gif
...
